services:
  konsolidator-ckg:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    environment:
      - DATABASE_HOST=mongodb
    ports:
      - "7272:7272"
    volumes:
      - .:/app
      - ./config.yaml:/app/config.yaml:ro
      - ./access.yaml:/app/access.yaml:ro
      - ./credentials.json:/app/credentials.json:ro
    networks:
      - xtb


networks:
  xtb:
    external: true
